export default {
	TIMER: "Timer",
	RECORDS: "Records",
	RECORD_DETAILS: "Record Details",
	STARRED_RECORDS: "Starred Records",
	ALGORITHM: "Algorithms",
	PLL_ALGORITHMS: "PLL Algorithms",
	OLL_ALGORITHMS: "OLL Algorithms",
	ALGORITHM_DETAILS: "Algorithm Details",
	SETTINGS: "Settings",
	MANAGE_RECORDS: "Manage Records",
	THEME: "Theme",
	DARK_THEME: "Dark Theme",
	LIGHT_THEME: "Light Theme",
};
