export default {
	TIMER: "Timer",
	RECORDS: "Records",
	RECORDS_AVG: "Average",
	RECORDS_AO5: "Average of 5",
	RECORDS_AO12: "Average of 12",
	STATISTICS: "Statistics",
	RECORD_DETAILS: "Record Details",
	STARRED_RECORDS: "Starred Records",
	ALGORITHM: "Algorithms",
	PLL_ALGORITHMS: "PLL Algorithms",
	OLL_ALGORITHMS: "OLL Algorithms",
	ALGORITHM_DETAILS: "Algorithm Details",
	SETTINGS: "Settings",
	MANAGE_RECORDS: "Manage Records",
	THEME: "Theme",
	DARK_THEME: "Dark Theme",
	LIGHT_THEME: "Light Theme",
};
